dependencies:
  - python=3.11.11
  - pip:
      - streamlit==1.32.0
      - pandas==2.0.3
      - numpy==1.24.3
      - matplotlib==3.7.2
      - plotly
      - pydantic-settings
      - psycopg2-binary